global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'booking-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5002']

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5003']

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5004']

  - job_name: 'review-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5005']

  - job_name: 'analytics-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5006']

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']


